CREATE TABLE USER_PLACE (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(250) NOT NULL,
	LATITUDE DECIMAL(10, 7) NOT NULL,
	LONGITUDE DECIMAL(10, 7) NOT NULL,
	OWNER_ID BIGINT NOT NULL,
	CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	MODIFIED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT PK_USER_PLACE PRIMARY KEY (ID),
	CONSTRAINT FK_USER_PLACE_USER FOREIGN KEY (OWNER_ID) REFERENCES USER(ID)
);