CREATE TABLE GOOGLE_PLACE (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	GOOGLE_ID VARCHAR(250) NULL,
	PLACE_ID BIGINT NOT NULL,
	ACTIVE BIT NOT NULL DEFAULT 1,
	CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	MODIFIED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT PK_GOOGLE_PLACE PRIMARY KEY (ID),	
	CONSTRAINT FK_GOOGLE_PLACE_PLACE FOREIGN KEY (PLACE_ID) REFERENCES PLACE(ID)
);

TRUNCATE USER_PLACE;

ALTER TABLE USER_PLACE
	DROP COLUMN NAME;
	
ALTER TABLE USER_PLACE
	DROP COLUMN LATITUDE;
	
ALTER TABLE USER_PLACE
	DROP COLUMN LONGITUDE;
	
ALTER TABLE USER_PLACE
	ADD COLUMN PLACE_ID BIGINT NOT NULL;
	
ALTER TABLE USER_PLACE
	ADD CONSTRAINT FK_USER_PLACE_PLACE FOREIGN KEY (PLACE_ID) REFERENCES PLACE(ID);
	
INSERT INTO GOOGLE_PLACE (GOOGLE_ID, PLACE_ID, ACTIVE, CREATE_DATE, MODIFIED_DATE)
SELECT 
	GOOGLE_PLACE_ID as GOOGLE_ID,
	ID as PLACE_ID,
	ACTIVE,
	CREATE_DATE,
	MODIFIED_DATE
FROM PLACE;

ALTER TABLE PLACE
	DROP COLUMN GOOGLE_PLACE_ID;
	
ALTER TABLE PLACE
	DROP COLUMN ACTIVE;