ALTER TABLE PLACE
	MODIFY COLUMN LATITUDE DOUBLE(10, 6) NOT NULL;
	
ALTER TABLE PLACE
	MODIFY COLUMN LONGITUDE DOUBLE(10, 6) NOT NULL;
	
ALTER TABLE READING
	MODIFY COLUMN LATITUDE DOUBLE(10, 6) NOT NULL;
	
ALTER TABLE READING
	MODIFY COLUMN LONGITUDE DOUBLE(10, 6) NOT NULL;
	