CREATE TABLE PLACE_VISIT (
	ID BIGINT NOT NULL AUTO_INCREMENT,	
	LATITUDE DOUBLE(10, 6) NOT NULL,
	LONGITUDE DECIMAL(10, 7) NOT NULL,
	PLACE_TYPE INT NOT NULL,
	VISIT_DATE DATETIME NULL,
	USER_SELECTED BIT NOT NULL DEFAULT 0,
	PLACE_ID BIGINT NOT NULL,
	OWNER_ID BIGINT NOT NULL,
	CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	MODIFIED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT PK_PLACE_VISIT PRIMARY KEY (ID),
	CONSTRAINT FK_PLACE_VISIT_PLACE FOREIGN KEY (PLACE_ID) REFERENCES PLACE(ID),
	CONSTRAINT FK_PLACE_VISIT_USER FOREIGN KEY (OWNER_ID) REFERENCES USER(ID)
);
