CREATE TABLE CAR_MAINTENANCE (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	CAR_ID BIGINT NOT NULL,
	TPYE BIGINT NOT NULL,
	NOTES VARCHAR(2000) NULL,
	DATE DATETIME NOT NULL,
	MILEAGE DOUBLE NOT NULL DEFAULT 0,
	CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	MODIFIED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT PK_CAR_MAINTENANCE PRIMARY KEY (ID),
	CONSTRAINT FK_CAR_MAINTENANCE_CAR FOREIGN KEY (CAR_ID) REFERENCES CAR(ID)
);
