const TRIP_STATUS = {
    NEW: 1,
    STARTED: 2,
    FINISHED: 3,
    PROCESSED: 4
};

const TRIP_STATUSES = [
    TRIP_STATUS.NEW,
    TRIP_STATUS.STARTED,
    TRIP_STATUS.FINISHED,
    TRIP_STATUS.PROCESSED
];

const CAR_MAINTENANCE_TYPE = {
    OIL_CHANGE: 1,
    TIRE_ROTATION: 2,
    AIR_FILTER_CHANGE: 3,
    CABIN_AIR_FILTER_CHANGE: 4,
    OTHER: 5
};

const CAR_MAINTENANCE_TYPES = [
    CAR_MAINTENANCE_TYPE.OIL_CHANGE,
    CAR_MAINTENANCE_TYPE.TIRE_ROTATION,
    CAR_MAINTENANCE_TYPE.AIR_FILTER_CHANGE,
    CAR_MAINTENANCE_TYPE.CABIN_AIR_FILTER_CHANGE,
    CAR_MAINTENANCE_TYPE.OTHER
];

const TRIP_POSSIBLE_PLACE_TYPE = {
    START: 1,
    DESTINATION: 2
};

const TRIP_POSSIBLE_PLACE_TYPES = [
    TRIP_POSSIBLE_PLACE_TYPE.START,
    TRIP_POSSIBLE_PLACE_TYPE.DESTINATION
];

const LOG_TYPE = {
    DEBUG: 1,
    INFO: 2,
    WARN: 3,
    ERROR: 4
};

const LOG_TYPES = [
    self.LOG_TYPE.DEBUG,
    self.LOG_TYPE.INFO,
    self.LOG_TYPE.WARN,
    self.LOG_TYPE.ERROR
];

const SORT_ORDER = {
    ASC: "ASC",
    DESC: "DESC"
};

const FILTER_OPERATION = {
    EQ: "eq", // EQUAL
    NE: "ne", // NOT EQUAL
    LTE: "lte", // LESS THAN OR EQUAL
    GTE: "gte", // GREATER THAN OR EQUAL
    LT: "lt", // LESS THAN
    GT: "gt", // GREATER THAN
    CONT: "cont" // CONTAINS
};

const FILTER_TYPE = {
    TEXT: "TEXT",
    DATE: "DATE",
    DROPDOWN: "DROPDOWN",
    DROPDOWN_COMPLEX: "DROPDOWN_COMPLEX"
};

const ALERT_TYPE_ERROR = "ERROR";
const ALERT_TYPE_SUCCESS = "SUCCESS";
const ALERT_TYPE_WARN = "WARN";
const ALERT_TYPE_INFO = "INFO";

const EVENT_ALERT_SHOW = "alert:show";
const EVENT_ALERT_CLEAR = "alert:clear";

const DEGREE_SYMBOL = String.fromCharCode(176);

export {
    TRIP_STATUS,
    TRIP_STATUSES,
    CAR_MAINTENANCE_TYPE,
    CAR_MAINTENANCE_TYPES,
    TRIP_POSSIBLE_PLACE_TYPE,
    TRIP_POSSIBLE_PLACE_TYPES,
    LOG_TYPE,
    LOG_TYPES,
    SORT_ORDER,
    FILTER_OPERATION,
    FILTER_TYPE,

    ALERT_TYPE_ERROR,
    ALERT_TYPE_SUCCESS,
    ALERT_TYPE_WARN,
    ALERT_TYPE_INFO,
    EVENT_ALERT_SHOW,
    EVENT_ALERT_CLEAR,

    DEGREE_SYMBOL
}