ALTER TABLE READER_LOG
  CHANGE COLUMN TYPE TYPE_OLD VARCHAR(50);
  
ALTER TABLE READER_LOG
  ADD COLUMN TYPE INT AFTER ID;
  
ALTER TABLE READER_LOG
  DROP FOREIGN KEY READER_LOG_ibfk_1;
  
  
DROP TABLE LOG_TYPE;

CREATE TABLE LOG_TYPE (
	ID INT NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	CONSTRAINT PK_LOG_TYPE PRIMARY KEY(ID)
);

INSERT INTO LOG_TYPE (ID, NAME) VALUES 
	(1, 'DEBUG'),
	(2, 'INFO'),
	(3, 'WARN'),
	(4, 'ERROR');


UPDATE READER_LOG RL
LEFT JOIN LOG_TYPE LT ON RL.TYPE_OLD = LT.NAME
SET
  RL.TYPE = LT.ID;
  
ALTER TABLE READER_LOG
  DROP COLUMN TYPE_OLD;
  
ALTER TABLE READER_LOG
  MODIFY COLUMN TYPE INT NOT NULL;
  
ALTER TABLE READER_LOG
  ADD CONSTRAINT FK_READER_LOG_LOG_TYPE FOREIGN KEY (TYPE) REFERENCES LOG_TYPE(ID);
  