using System;
using System.Collections.Generic;
using System.Text;

namespace CarTracker.Common.Enums
{
    public enum ObdCommand
    {
        MonitorStatus = 1,
        FreezeDtc,
        FuelSystemStatus,
        CalculatedEngineLoad,
        EngineCoolantTemperature,
        ShortTermFuelTrimBank1,
        LongTermFuelTrimBank1,
        ShortTermFuelTrimBank2,
        LongTermFuelTrimBank2,
        FuelPressure,
        IntakeManifoldAbsolutePressure,
        EngineRpm,
        VehicleSpeed,
        TimingAdvance,
        IntakeAirTemperature,
        MassAirFlow,
        ThrottlePosition,
        CommandedSecondaryAirStatus,
        OxygenSensorsPresentBanks2,
        OxygenSensor1,
        OxygenSensor2,
        OxygenSensor3,
        OxygenSensor4,
        OxygenSensor5,
        OxygenSensor6,
        OxygenSensor7,
        OxygenSensor8,
        ObdStandards,
        OxygenSensorsPresentBanks4,
        AuxiliaryInputStatus,
        RunTimeSinceEngineStart,
        DistanceTraveledWithMilOn,
        FuelRailPressure,
        FuelRailGaugePressure,
        CommandedEgr,
        EgrError,
        CommandedEvaporatePurge,
        FuelTankLevelInput,
        WarmUpsSinceCodesCleared,
        DistanceTraveledSinceCodesCleared,
        EvapSystemVaporPressure,
        AbsoluteBarometricPressure,
        CatalystTemperatureBank1Sensor1,
        CatalystTemperatureBank2Sensor1,
        CatalystTemperatureBank1Sensor2,
        CatalystTemperatureBank2Sensor2,
        MonitorStatusThisDriveCycle,
        ControlModuleVoltage,
        AbsoluteLoadValue,
        FuelAirCommandedEquivalenceRation,
        RelativeThrottlePosition,
        AmbientAirTemperature,
        AbsoluteThrottlePositionB,
        AbsoluteThrottlePositionC,
        AbsoluteThrottlePositionD,
        AbsoluteThrottlePositionE,
        AbsoluteThrottlePositionF,
        CommandedThrottleActuator,
        TimeRunWithMilOn,
        TimeSinceTroubleCodesCleared,
        MaxFuelAirEquivalenceRation,
        MaxMaf,
        FuelType,
        EthanolFuelPercent,
        AbsoluteEvapSystemVaporPressure,
        FuelRailAbsolutePressure,
        RelativeAcceleratorPedalPosition,
        HybridBatteryPackRemainingLife,
        EngineOilTemperature,
        FuelInjectionTiming,
        EngineFuelRate,
        EmissionsRequirementsStandards,
        DriversDemandEngineTorquePercent,
        ActualEngineTorquePercent,
        EngineReferenceTorque,
        EngineTorquePercent,
        ExhauseGasRecirculationTemperature,
        TurbochargerCompressorInletPressure,
        BoostPressureControl,
        WastegateControl,
        ExhaustPressure,
        TurbochargerRpm,
        TurbochargerTemperature1,
        TurbochargerTemperature2,
        ChargeAirCoolerTemperature,
        ExhaustGasTemperatureBank1,
        ExhaustGasTemperatureBank2,
        EngineRunTime
    }

    public static class ObdCommandExtensions
    {
        private static readonly Dictionary<ObdCommand, string> CommandNames = new Dictionary<ObdCommand, string>()
        {
            {ObdCommand.MonitorStatus, "Monitor status since DTCs cleared"},
            {ObdCommand.FreezeDtc, "Freeze DTC"},
            {ObdCommand.FuelSystemStatus, "Fuel system status"},
            {ObdCommand.CalculatedEngineLoad, "Calculated engine load"},
            {ObdCommand.EngineCoolantTemperature, "Engine coolant temperature"},
            {ObdCommand.ShortTermFuelTrimBank1, "Short term fuel trim - Bank 1"},
            {ObdCommand.LongTermFuelTrimBank1, "Long term fuel trim - Bank 1"},
            {ObdCommand.ShortTermFuelTrimBank2, "Short term fuel trim - Bank 2"},
            {ObdCommand.LongTermFuelTrimBank2, "Long term fuel trim - Bank 2"},
            {ObdCommand.FuelPressure, "Fuel pressure"},
            {ObdCommand.IntakeManifoldAbsolutePressure, "Intake manifold absolute pressure"},
            {ObdCommand.EngineRpm, "Engine RPM"},
            {ObdCommand.VehicleSpeed, "Vehicle speed"},
            {ObdCommand.TimingAdvance, "Timing Advance"},
            {ObdCommand.IntakeAirTemperature, "Intake air temperature"},
            {ObdCommand.MassAirFlow, "Mass air flow rate"},
            {ObdCommand.ThrottlePosition, "Throttle Position"},
            {ObdCommand.CommandedSecondaryAirStatus, "Commanded secondary air status"},
            {ObdCommand.OxygenSensorsPresentBanks2, "Oxygen sensors present"},
            {ObdCommand.OxygenSensor1, "Oxygen Sensor 1"},
            {ObdCommand.OxygenSensor2, "Oxygen Sensor 2"},
            {ObdCommand.OxygenSensor3, "Oxygen Sensor 3"},
            {ObdCommand.OxygenSensor4, "Oxygen Sensor 4"},
            {ObdCommand.OxygenSensor5, "Oxygen Sensor 5"},
            {ObdCommand.OxygenSensor6, "Oxygen Sensor 6"},
            {ObdCommand.OxygenSensor7, "Oxygen Sensor 7"},
            {ObdCommand.OxygenSensor8, "Oxygen Sensor 8"},
            {ObdCommand.ObdStandards, "OBD Standards"},
            {ObdCommand.OxygenSensorsPresentBanks4, "Oxygen seensors present (4 banks)"},
            {ObdCommand.AuxiliaryInputStatus, "Auxiliary input status"},
            {ObdCommand.RunTimeSinceEngineStart, "Run time since engine start"},
            {ObdCommand.DistanceTraveledWithMilOn, "Distance traveled with MIL on"},
            {ObdCommand.FuelRailPressure, "Fuel rail pressure"},
            {ObdCommand.FuelRailGaugePressure, "Fuel rail gauge pressure"},
            {ObdCommand.CommandedEgr, "Commanded EGR"},
            {ObdCommand.EgrError, "EGR Error"},
            {ObdCommand.CommandedEvaporatePurge, "Commanded evaporative purge"},
            {ObdCommand.FuelTankLevelInput, "Fuel tank level input"},
            {ObdCommand.WarmUpsSinceCodesCleared, "Warm-ups since codes cleared"},
            {ObdCommand.DistanceTraveledSinceCodesCleared, "Distance traveled since codes cleared"},
            {ObdCommand.EvapSystemVaporPressure, "Evap system vapor pressure"},
            {ObdCommand.AbsoluteBarometricPressure, "Absolute barometric pressure"},
            {ObdCommand.CatalystTemperatureBank1Sensor1, "Catalist temperature Bank 1 Sensor 1"},
            {ObdCommand.CatalystTemperatureBank2Sensor1, "Catalist temperature Bank 2 Sensor 1"},
            {ObdCommand.CatalystTemperatureBank1Sensor2, "Catalist temperature Bank 1 Sensor 2"},
            {ObdCommand.CatalystTemperatureBank2Sensor2, "Catalist temperature Bank 2 Sensor 2"},
            {ObdCommand.MonitorStatusThisDriveCycle, "Monitor stauts this drive cycle"},
            {ObdCommand.ControlModuleVoltage, "Control module voltage"},
            {ObdCommand.AbsoluteLoadValue, "Absolute load value"},
            {ObdCommand.FuelAirCommandedEquivalenceRation, "Fuel air commanded equivalence ratio"},
            {ObdCommand.RelativeThrottlePosition, "Relative throttle position"},
            {ObdCommand.AmbientAirTemperature, "Ambient air temperature"},
            {ObdCommand.AbsoluteThrottlePositionB, "Absolute throttle position B"},
            {ObdCommand.AbsoluteThrottlePositionC, "Absolute throttle position C"},
            {ObdCommand.AbsoluteThrottlePositionD, "Absolute throttle position F"},
            {ObdCommand.AbsoluteThrottlePositionE, "Absolute throttle position E"},
            {ObdCommand.AbsoluteThrottlePositionF, "Absolute throttle position F"},
            {ObdCommand.CommandedThrottleActuator, "Commanded throttle actuator"},
            {ObdCommand.TimeRunWithMilOn, "Time run with MIL on"},
            {ObdCommand.TimeSinceTroubleCodesCleared, "Time since trouble codes cleared"},
            {ObdCommand.MaxFuelAirEquivalenceRation, "Maximum value for Fuel Air equivalence ratio"},
            {ObdCommand.MaxMaf, "Maximum value for MAF"},
            {ObdCommand.FuelType, "Fuel type"},
            {ObdCommand.EthanolFuelPercent, "Ethanol fuel %"},
            {ObdCommand.AbsoluteEvapSystemVaporPressure, "Absolute evap system vapor pressure"},
            {ObdCommand.FuelRailAbsolutePressure, "Fuel rail absolute pressure"},
            {ObdCommand.RelativeAcceleratorPedalPosition, "Relative accelerator pedal position"},
            {ObdCommand.HybridBatteryPackRemainingLife, "Hybird battery pack remaining life"},
            {ObdCommand.EngineOilTemperature, "Engine oil temperature"},
            {ObdCommand.FuelInjectionTiming, "Fuel injection timing"},
            {ObdCommand.EngineFuelRate, "Engine fuel rate"},
            {ObdCommand.EmissionsRequirementsStandards, "Emission requirement standards"},
            {ObdCommand.DriversDemandEngineTorquePercent, "Driver's demand engine % torque"},
            {ObdCommand.ActualEngineTorquePercent, "Actual engine % torque"},
            {ObdCommand.EngineReferenceTorque, "Engine reference torque"},
            {ObdCommand.EngineTorquePercent, "Engine % torque"},
            {ObdCommand.ExhauseGasRecirculationTemperature, "Exhaust gas reciculation temperature"},
            {ObdCommand.TurbochargerCompressorInletPressure, "Turbo charger compressor inlet pressure"},
            {ObdCommand.BoostPressureControl, "Boost pressure control"},
            {ObdCommand.WastegateControl, "Wastegate control"},
            {ObdCommand.ExhaustPressure, "Exhaust pressure"},
            {ObdCommand.TurbochargerRpm, "Turbocharger RPM"},
            {ObdCommand.TurbochargerTemperature1, "Turbocharger temperature 1"},
            {ObdCommand.TurbochargerTemperature2, "Turbocharger temperature 2"},
            {ObdCommand.ChargeAirCoolerTemperature, "Charge air cooler temperature"},
            {ObdCommand.ExhaustGasTemperatureBank1, "Exhaust gas temperature Bank 1"},
            {ObdCommand.ExhaustGasTemperatureBank2, "Exhaust gas temperature Bank 2"},
            {ObdCommand.EngineRunTime, "Engine run time"}
        };

        public static string GetName(this ObdCommand command)
        {
            if (CommandNames.ContainsKey(command))
            {
                return CommandNames[command];
            }
            return command.ToString();
        }
    }
}
