CREATE TABLE PLACE_TYPE (
	ID INT NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	MODIFIED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT PK_PLACE_TYPE PRIMARY KEY (ID),
	CONSTRAINT PK_PLACE_TYPE_NAME UNIQUE (NAME)
);