CREATE TABLE REQUEST_LOG (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	REQUEST_UUID VARCHAR(64) NOT NULL,
	TYPE INT NOT NULL,
	CLIENT_ADDRESS VARCHAR(255) NULL,	
	REQUEST_URL VARCHAR(255) NULL,
	REQUEST_METHOD VARCHAR (50) NULL,	
	RESPONSE_STATUS VARCHAR(10) NULL,
	CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	MODIFIED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	REQUEST_BODY TEXT NULL,	
	RESPONSE_BODY TEXT  NULL,		
	CONSTRAINT PK_REQUEST_LOG PRIMARY KEY (ID)
);