CREATE TABLE TRIP_STATUS (
	ID INT NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	DESCRIPTION VARCHAR(500) NOT NULL,
	CREATE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	MODIFIED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT PK_TRIP_STATUS PRIMARY KEY (ID),
	CONSTRAINT PK_TRIP_NAME UNIQUE (NAME)
);